"""
app/services/weak_topic_mode.py
-------------------------------
Weak Topic Mode aggregator for issue #15 acceptance criterion #2.

This module is a thin orchestration layer on top of the existing
clustering + ROI primitives in `gap_analyzer.py`. It does not introduce
any new persisted state. Its job is to reshape the existing per-topic
data into the issue-15-mandated response:

    1. Top weak topics grouped by subject.
    2. Per-topic action bundle: learn (textbook), tutor (chat), practice,
       retest. Each action is a deterministic, bookmarkable URL fragment.
    3. A 7-day recovery plan synthesized deterministically from the
       prioritized topic list. No LLM call, no motivational filler.

The 7-day plan is intentionally NOT generated by an LLM. The Strategy
Lab roadmap (`strategy_service.generate_strategy`) already covers
LLM-prose week-level guidance; we want the per-topic operational view
to be reproducible and testable.

Pure helpers (subject grouping, action URL resolution, plan synthesis)
are factored out so tests can run without a DB session.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import asdict, dataclass
from typing import Literal

from sqlalchemy.ext.asyncio import AsyncSession

from app.constants.subjects import (
    get_compulsory_subjects,
    get_profile_subjects,
    is_valid_subject,
    normalize_subject_name,
)
from app.services.gap_analyzer import (
    cluster_mistakes_by_topic,
    estimate_pages_for_topic,
    generate_recommendations,
    get_user_target_threshold,
)

WeakTopicActionKind = Literal["learn", "tutor", "practice", "retest"]
PlanIntent = Literal["learn", "practice", "retest", "review"]

# How many topics we surface per subject in the gap map. Beyond this we
# truncate to keep the page legible; users can click into Mistakes for
# full history.
TOP_TOPICS_PER_SUBJECT = 5

# 7-day plan composition. The recovery loop is:
#   day 1: learn the heaviest topic
#   day 2: practice the same topic
#   day 3: learn the second-heaviest
#   day 4: practice the second-heaviest
#   day 5: review (mistakes page) for both
#   day 6: practice mixed
#   day 7: retest via a fresh exam
# This pattern is deterministic; tests assert it byte-for-byte.
SEVEN_DAY_PLAN_INTENTS: tuple[PlanIntent, ...] = (
    "learn",
    "practice",
    "learn",
    "practice",
    "review",
    "practice",
    "retest",
)


@dataclass(frozen=True)
class WeakTopicAction:
    """One actionable next step bound to a single topic."""

    kind: WeakTopicActionKind
    href: str
    # The subject is carried so the FE can render "Practice in Math" without
    # re-deriving from the topic string.
    subject: str | None = None

    def to_dict(self) -> dict[str, object]:
        return {"kind": self.kind, "href": self.href, "subject": self.subject}


@dataclass(frozen=True)
class WeakTopicEntry:
    """One weak topic with its action bundle and ROI metadata."""

    topic: str
    subject: str
    points_lost: int
    mistake_count: int
    pages_to_read: int
    priority: Literal["HIGH", "MEDIUM", "LOW"]
    actions: tuple[WeakTopicAction, ...]

    def to_dict(self) -> dict[str, object]:
        payload = asdict(self)
        payload["actions"] = [a.to_dict() for a in self.actions]
        return payload


@dataclass(frozen=True)
class WeakTopicSubjectGroup:
    """One subject's weak topics, top-N by points lost."""

    subject: str
    total_points_lost: int
    topics: tuple[WeakTopicEntry, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "subject": self.subject,
            "total_points_lost": self.total_points_lost,
            "topics": [t.to_dict() for t in self.topics],
        }


@dataclass(frozen=True)
class WeakTopicPlanDay:
    """One day in the 7-day recovery plan."""

    day: int  # 1..7
    intent: PlanIntent
    topic: str | None
    subject: str | None
    href: str

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


# ----- Pure helpers (no DB) -----------------------------------------------


def derive_subject_from_topic(topic: str) -> str:
    """
    Best-effort topic-tag → subject mapping.

    `MistakeReview.topic_tag` is a free-form string written by the
    AI diagnosis step. Examples observed in the wild:

        "Mathematics"
        "History > 18th Century"
        "Physics: Mechanics"
        "Chemistry > Organic > Hydrocarbons"

    We split on the first ">", ":" or "-", normalize, and verify
    against the canonical subject list. Anything that doesn't match
    is bucketed as "Other" so the FE can still render it.

    This function is pure and is the same on every invocation given the
    same input. Tests pin a representative set.
    """

    if not topic:
        return "Other"

    head = topic
    for separator in (">", ":", " - ", " — "):
        if separator in head:
            head = head.split(separator, 1)[0]
            break
    head = head.strip()

    normalized = normalize_subject_name(head) if head else ""
    if normalized and is_valid_subject(normalized):
        return normalized

    # Some topic tags use lowercase or alternate casing. Try the raw head.
    if head and is_valid_subject(head):
        return head

    return "Other"


def build_topic_actions(*, topic: str, subject: str) -> tuple[WeakTopicAction, ...]:
    """
    Resolve the four URL fragments that satisfy issue #15 AC #3:
    learn (textbook search), tutor (chat seeded with topic), practice
    (generator filtered to subject), retest (exam start).

    These are deterministic FE-routable hrefs. The backend does not
    open any of them; the FE attaches them to chips. Encoding is plain
    URL-encoded query params so a deep-link works without a router
    state object.

    No LLM, no DB call.
    """
    # We use `+` style space encoding (safe for query strings) to keep
    # tests human-readable.
    safe_topic = _url_safe(topic)
    safe_subject = _url_safe(subject) if subject and subject != "Other" else ""

    learn_href = f"/dashboard/library?q={safe_topic}"
    if safe_subject:
        learn_href += f"&subject={safe_subject}"

    tutor_href = f"/dashboard/chat?topic={safe_topic}"
    if safe_subject:
        tutor_href += f"&subject={safe_subject}"

    practice_href = "/dashboard/quiz"
    if safe_subject:
        practice_href += f"?subject={safe_subject}"

    retest_href = "/dashboard/exams"

    return (
        WeakTopicAction(kind="learn", href=learn_href, subject=subject or None),
        WeakTopicAction(kind="tutor", href=tutor_href, subject=subject or None),
        WeakTopicAction(kind="practice", href=practice_href, subject=subject or None),
        WeakTopicAction(kind="retest", href=retest_href, subject=subject or None),
    )


def _url_safe(value: str) -> str:
    """Minimal URL-safe encoding for query values.

    Avoids importing `urllib.parse.quote_plus` per call; the inputs are
    short topic/subject labels with bounded character set. Keep
    Cyrillic and ASCII letters; replace everything else with `%xx` for
    bytes outside that band, and replace whitespace with `+`.
    """
    from urllib.parse import quote_plus

    return quote_plus(value or "")


def group_topics_by_subject(
    topic_clusters: Iterable[dict],
    *,
    page_estimates: dict[str, int] | None = None,
    top_n: int = TOP_TOPICS_PER_SUBJECT,
) -> tuple[WeakTopicSubjectGroup, ...]:
    """
    Take the flat list returned by `cluster_mistakes_by_topic` and
    reshape it into a per-subject grouping.

    `topic_clusters`: iterable of dicts with keys `topic`,
    `points_lost`, `mistake_count`. We trust the caller has already
    filtered out resolved mistakes (this is what `cluster_mistakes_by_topic`
    does by default).

    `page_estimates`: optional precomputed mapping topic→pages so this
    function stays sync. The router calls `estimate_pages_for_topic`
    once per topic before invoking us.

    Topics within a subject are sorted by points lost desc, mistake
    count desc, topic asc. Subjects themselves are sorted by total
    points lost desc, then alphabetically. We truncate each subject's
    topics to `top_n` to avoid runaway lists.

    HIGH/MEDIUM/LOW priority: same thresholds gap_analyzer uses
    (efficiency = points_lost / pages, ≥0.5 high, ≥0.2 medium).
    """
    page_estimates = page_estimates or {}

    by_subject: dict[str, list[WeakTopicEntry]] = {}
    subject_total: dict[str, int] = {}

    for cluster in topic_clusters:
        topic = (cluster.get("topic") or "").strip()
        if not topic:
            continue
        points_lost = int(cluster.get("points_lost") or 0)
        mistake_count = int(cluster.get("mistake_count") or 0)
        if points_lost <= 0 and mistake_count <= 0:
            continue

        subject = derive_subject_from_topic(topic)
        pages = max(int(page_estimates.get(topic, 10) or 10), 1)
        efficiency = points_lost / pages
        if efficiency >= 0.5:
            priority: Literal["HIGH", "MEDIUM", "LOW"] = "HIGH"
        elif efficiency >= 0.2:
            priority = "MEDIUM"
        else:
            priority = "LOW"

        actions = build_topic_actions(topic=topic, subject=subject)
        entry = WeakTopicEntry(
            topic=topic,
            subject=subject,
            points_lost=points_lost,
            mistake_count=mistake_count,
            pages_to_read=pages,
            priority=priority,
            actions=actions,
        )
        by_subject.setdefault(subject, []).append(entry)
        subject_total[subject] = subject_total.get(subject, 0) + points_lost

    groups: list[WeakTopicSubjectGroup] = []
    for subject, entries in by_subject.items():
        entries.sort(
            key=lambda e: (-e.points_lost, -e.mistake_count, e.topic),
        )
        truncated = tuple(entries[: max(top_n, 1)])
        groups.append(
            WeakTopicSubjectGroup(
                subject=subject,
                total_points_lost=subject_total.get(subject, 0),
                topics=truncated,
            )
        )

    groups.sort(key=lambda g: (-g.total_points_lost, g.subject))
    return tuple(groups)


def synthesize_seven_day_plan(
    groups: Iterable[WeakTopicSubjectGroup],
) -> tuple[WeakTopicPlanDay, ...]:
    """
    Build a 7-day plan from the prioritized subject groups.

    The plan template is `SEVEN_DAY_PLAN_INTENTS`. We pick the top two
    topics across all subjects (by points lost) and rotate them through
    the template:

        day 1 learn  → top-1 topic
        day 2 practice → top-1 topic
        day 3 learn  → top-2 topic
        day 4 practice → top-2 topic
        day 5 review → mistakes page (no specific topic)
        day 6 practice → top-1 topic again (lock in)
        day 7 retest → /dashboard/exams (no specific topic)

    If there are fewer than 2 topics with weight, the plan still
    returns 7 days, but missing topic days collapse to the review day's
    href. This avoids empty render branches on the FE.
    """
    flat: list[WeakTopicEntry] = []
    for group in groups:
        flat.extend(group.topics)
    flat.sort(key=lambda e: (-e.points_lost, -e.mistake_count, e.topic))

    top1 = flat[0] if len(flat) >= 1 else None
    top2 = flat[1] if len(flat) >= 2 else None

    days: list[WeakTopicPlanDay] = []
    for i, intent in enumerate(SEVEN_DAY_PLAN_INTENTS):
        day_n = i + 1
        if intent == "learn" and day_n == 1 and top1 is not None:
            target, kind = top1, "learn"
        elif intent == "practice" and day_n == 2 and top1 is not None:
            target, kind = top1, "practice"
        elif intent == "learn" and day_n == 3 and top2 is not None:
            target, kind = top2, "learn"
        elif intent == "practice" and day_n == 4 and top2 is not None:
            target, kind = top2, "practice"
        elif intent == "review":
            days.append(
                WeakTopicPlanDay(
                    day=day_n,
                    intent="review",
                    topic=None,
                    subject=None,
                    href="/dashboard/mistakes",
                )
            )
            continue
        elif intent == "practice" and day_n == 6 and top1 is not None:
            target, kind = top1, "practice"
        elif intent == "retest":
            days.append(
                WeakTopicPlanDay(
                    day=day_n,
                    intent="retest",
                    topic=None,
                    subject=None,
                    href="/dashboard/exams",
                )
            )
            continue
        else:
            # No topic available for this slot — degrade gracefully
            # to a review day rather than rendering an empty card.
            days.append(
                WeakTopicPlanDay(
                    day=day_n,
                    intent="review",
                    topic=None,
                    subject=None,
                    href="/dashboard/mistakes",
                )
            )
            continue

        # Pick the matching action href so the day card deep-links.
        href = next(
            (a.href for a in target.actions if a.kind == kind),
            "/dashboard/mistakes",
        )
        days.append(
            WeakTopicPlanDay(
                day=day_n,
                intent=intent,
                topic=target.topic,
                subject=target.subject,
                href=href,
            )
        )

    return tuple(days)


def expected_subjects() -> tuple[str, ...]:
    """The subjects we expect to see in the Weak Topic Mode response.

    This is the union of compulsory + profile subjects. Used by the FE
    only as a hint for empty-state copy ("you have no weak topics yet
    in your tracked subjects"). The BE does NOT filter responses to
    only these — Other-bucketed topics still show up.
    """
    seen: list[str] = []
    for name in get_compulsory_subjects() + get_profile_subjects():
        if name not in seen:
            seen.append(name)
    return tuple(seen)


# ----- Async orchestrator -------------------------------------------------


async def build_weak_topic_mode_response(user_id: int, db: AsyncSession) -> dict[str, object]:
    """
    Compose the full /analytics/weak-topic-mode payload.

    Reuses:
      - get_user_target_threshold (for the gap header context)
      - cluster_mistakes_by_topic (the canonical weak-topic source)
      - estimate_pages_for_topic (per-topic page estimate)
      - generate_recommendations (only to surface current_score
        + total_recoverable_points; we re-cluster ourselves to keep
        the per-subject grouping crisp)

    The router converts this dict into a Pydantic response_model. We
    return a plain dict here to keep the service free of FastAPI deps.
    """
    threshold_info = await get_user_target_threshold(user_id, db)
    recommendations_payload = await generate_recommendations(user_id, db)

    clusters = await cluster_mistakes_by_topic(user_id, db)

    page_estimates: dict[str, int] = {}
    for cluster in clusters:
        topic = (cluster.get("topic") or "").strip()
        if not topic or topic in page_estimates:
            continue
        page_estimates[topic] = await estimate_pages_for_topic(topic, db)

    groups = group_topics_by_subject(clusters, page_estimates=page_estimates)
    plan = synthesize_seven_day_plan(groups)

    return {
        "target_university": threshold_info.get("university_name"),
        "grant_threshold": threshold_info.get("grant_threshold"),
        "current_score": recommendations_payload.get("current_score"),
        "current_score_source": recommendations_payload.get("current_score_source"),
        "gap": recommendations_payload.get("gap"),
        "total_recoverable_points": recommendations_payload.get("total_recoverable_points", 0),
        "expected_subjects": list(expected_subjects()),
        "subject_groups": [g.to_dict() for g in groups],
        "seven_day_plan": [d.to_dict() for d in plan],
    }
