"""initial_schema

Revision ID: d2c3606882dd
Revises: 3c3bc4460109
Create Date: 2026-04-07 22:29:24.930301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c3606882dd'
down_revision: Union[str, Sequence[str], None] = '3c3bc4460109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_code', sa.String(), nullable=False),
    sa.Column('major_code', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quota_type', sa.String(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('grants_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_code', 'major_code', 'year', 'quota_type', name='uq_acceptance_score')
    )
    op.create_index('ix_acceptance_lookup', 'acceptance_scores', ['university_code', 'major_code', 'year'], unique=False)
    op.create_index(op.f('ix_acceptance_scores_id'), 'acceptance_scores', ['id'], unique=False)
    op.create_index(op.f('ix_acceptance_scores_major_code'), 'acceptance_scores', ['major_code'], unique=False)
    op.create_index(op.f('ix_acceptance_scores_university_code'), 'acceptance_scores', ['university_code'], unique=False)
    op.create_index(op.f('ix_acceptance_scores_year'), 'acceptance_scores', ['year'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('question_text_kz', sa.Text(), nullable=False),
    sa.Column('question_text_ru', sa.Text(), nullable=False),
    sa.Column('options_kz', sa.JSON(), nullable=False),
    sa.Column('options_ru', sa.JSON(), nullable=False),
    sa.Column('correct_answers_indices', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('context_stimulus_kz', sa.Text(), nullable=True),
    sa.Column('context_stimulus_ru', sa.Text(), nullable=True),
    sa.Column('context_group_id', sa.String(), nullable=True),
    sa.Column('matching_pairs', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('correct_order', sa.JSON(), nullable=True),
    sa.Column('accepted_answers', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_context_group_id'), 'exam_questions', ['context_group_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_id'), 'exam_questions', ['id'], unique=False)
    op.create_index(op.f('ix_exam_questions_source_id'), 'exam_questions', ['source_id'], unique=True)
    op.create_index(op.f('ix_exam_questions_subject'), 'exam_questions', ['subject'], unique=False)
    op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_table('langchain_pg_embedding')
    op.drop_index(op.f('ix_telemetry_logs_component'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_created_at'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_level'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_user_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_student_profile_id'), table_name='student_profile')
    op.drop_table('student_profile')
    op.drop_index(op.f('ix_telemetry_errors_category'), table_name='telemetry_errors')
    op.drop_index(op.f('ix_telemetry_errors_created_at'), table_name='telemetry_errors')
    op.drop_index(op.f('ix_telemetry_errors_id'), table_name='telemetry_errors')
    op.drop_index(op.f('ix_telemetry_errors_severity'), table_name='telemetry_errors')
    op.drop_index(op.f('ix_telemetry_errors_user_id'), table_name='telemetry_errors')
    op.drop_table('telemetry_errors')
    op.drop_index(op.f('ix_telemetry_bugs_created_at'), table_name='telemetry_bugs')
    op.drop_index(op.f('ix_telemetry_bugs_id'), table_name='telemetry_bugs')
    op.drop_index(op.f('ix_telemetry_bugs_severity'), table_name='telemetry_bugs')
    op.drop_index(op.f('ix_telemetry_bugs_status'), table_name='telemetry_bugs')
    op.drop_table('telemetry_bugs')
    op.drop_index(op.f('ix_telemetry_requests_created_at'), table_name='telemetry_requests')
    op.drop_index(op.f('ix_telemetry_requests_id'), table_name='telemetry_requests')
    op.drop_index(op.f('ix_telemetry_requests_path'), table_name='telemetry_requests')
    op.drop_index(op.f('ix_telemetry_requests_status_code'), table_name='telemetry_requests')
    op.drop_index(op.f('ix_telemetry_requests_user_id'), table_name='telemetry_requests')
    op.drop_table('telemetry_requests')
    op.drop_table('langchain_pg_collection')
    op.add_column('mock_questions', sa.Column('subject', sa.String(), nullable=True))
    op.alter_column('mock_questions', 'topic_tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mock_questions', 'question_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('mock_questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('mock_questions', 'correct_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_mock_questions_topic_tag'), table_name='mock_questions')
    op.create_index(op.f('ix_mock_questions_subject'), 'mock_questions', ['subject'], unique=False)
    op.drop_column('mock_questions', 'difficulty')
    op.alter_column('university_data', 'uni_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('university_data', 'major_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('university_data', 'major_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('university_data', 'min_score_paid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('university_data', 'grant_threshold_general',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_university_data_major_name'), table_name='university_data')
    op.create_index(op.f('ix_university_data_major_code'), 'university_data', ['major_code'], unique=False)
    op.drop_column('university_data', 'city')
    op.drop_column('university_data', 'tuition_per_year')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'language_preference',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('KZ', 'RU', 'EN', name='languagepreference'),
               existing_nullable=True,
               existing_server_default=sa.text("'EN'::character varying"))
    op.alter_column('users', 'moderation_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_users_email_unique'), table_name='users', postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_email_unique'), 'users', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('users', 'moderation_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'language_preference',
               existing_type=sa.Enum('KZ', 'RU', 'EN', name='languagepreference'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'EN'::character varying"))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'is_admin')
    op.add_column('university_data', sa.Column('tuition_per_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('university_data', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_university_data_major_code'), table_name='university_data')
    op.create_index(op.f('ix_university_data_major_name'), 'university_data', ['major_name'], unique=False)
    op.alter_column('university_data', 'grant_threshold_general',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('university_data', 'min_score_paid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('university_data', 'major_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('university_data', 'major_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('university_data', 'uni_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('mock_questions', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mock_questions_subject'), table_name='mock_questions')
    op.create_index(op.f('ix_mock_questions_topic_tag'), 'mock_questions', ['topic_tag'], unique=False)
    op.alter_column('mock_questions', 'correct_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mock_questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('mock_questions', 'question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('mock_questions', 'topic_tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('mock_questions', 'subject')
    op.create_table('langchain_pg_collection',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey')),
    sa.UniqueConstraint('name', name=op.f('langchain_pg_collection_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('telemetry_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('query_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('response_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_requests_pkey'))
    )
    op.create_index(op.f('ix_telemetry_requests_user_id'), 'telemetry_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_telemetry_requests_status_code'), 'telemetry_requests', ['status_code'], unique=False)
    op.create_index(op.f('ix_telemetry_requests_path'), 'telemetry_requests', ['path'], unique=False)
    op.create_index(op.f('ix_telemetry_requests_id'), 'telemetry_requests', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_requests_created_at'), 'telemetry_requests', ['created_at'], unique=False)
    op.create_table('telemetry_bugs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('steps_to_reproduce', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expected_behavior', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actual_behavior', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severitylevel'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='bugstatus'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_bugs_pkey'))
    )
    op.create_index(op.f('ix_telemetry_bugs_status'), 'telemetry_bugs', ['status'], unique=False)
    op.create_index(op.f('ix_telemetry_bugs_severity'), 'telemetry_bugs', ['severity'], unique=False)
    op.create_index(op.f('ix_telemetry_bugs_id'), 'telemetry_bugs', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_bugs_created_at'), 'telemetry_bugs', ['created_at'], unique=False)
    op.create_table('telemetry_errors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severitylevel'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('environment', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_errors_pkey'))
    )
    op.create_index(op.f('ix_telemetry_errors_user_id'), 'telemetry_errors', ['user_id'], unique=False)
    op.create_index(op.f('ix_telemetry_errors_severity'), 'telemetry_errors', ['severity'], unique=False)
    op.create_index(op.f('ix_telemetry_errors_id'), 'telemetry_errors', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_errors_created_at'), 'telemetry_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_errors_category'), 'telemetry_errors', ['category'], unique=False)
    op.create_table('student_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chosen_subjects', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('raw_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quota_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_tolerance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('student_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('student_profile_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_student_profile_id'), 'student_profile', ['id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_logs_pkey'))
    )
    op.create_index(op.f('ix_telemetry_logs_user_id'), 'telemetry_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_level'), 'telemetry_logs', ['level'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_created_at'), 'telemetry_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_component'), 'telemetry_logs', ['component'], unique=False)
    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_index(op.f('ix_cmetadata_gin'), 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_exam_questions_subject'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_source_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_context_group_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_acceptance_scores_year'), table_name='acceptance_scores')
    op.drop_index(op.f('ix_acceptance_scores_university_code'), table_name='acceptance_scores')
    op.drop_index(op.f('ix_acceptance_scores_major_code'), table_name='acceptance_scores')
    op.drop_index(op.f('ix_acceptance_scores_id'), table_name='acceptance_scores')
    op.drop_index('ix_acceptance_lookup', table_name='acceptance_scores')
    op.drop_table('acceptance_scores')
    # ### end Alembic commands ###
